### ISSUE TITLE
Не работает wrk.sh :)

### ISSUE THREAD

**Issue by makorne** [dedok/tnt-accounts#1]
Пробую тесты...
> ./t/basic_test.py
> [+] /add/user
> (200, {u'id': 0, u'result': [{u'user_name': u'Vasiliy', u'account_id': 1531249206, u'id': 2}]})
> [+] OK

> ./t/wrk.sh
> [+] add users
> ./t/wrk.sh: line 10: wrk: command not found

Как wrk.sh заставить работать?

**Comment by dedok** [comment]
Привет,

Надо поставить wrk :) Например: yum install wrk или brew install wrk.

**Comment by makorne** [comment]
Спасибо, первый раз слышу о такой тулзе
А как дебажить при запуске этой докер-связки? 
print выводит  только 1 строчку 1 раз на запуск.
Если выводить значения через print в двух местах, то выводит лишь один, и то один раз, если добавишь например сумму первый раз - выведет, а повторно - нет, хотя в базу положит.И не будет выводить пока не перезапустишь эту связку

**Comment by dedok** [comment]
Привет,

Немного не понял вопроса :) Ты можешь мне на почту (dedok.mad@gmail.com) написать? В ответ я вышлю свою телегу или ты вышли свою.

PS
Не очень это удобно общаться используя GH issues.

PSS
WRK - тулза для нагрузочного тестирования HTTP(S), кмк, достаточно удобная.
